Performance improvements
Songoda-Plugins/EpicSpawners pull request #17
Opened 2023-09-05 20:21 UTC by Tom18314

Just some performance improvements. The database thing really helps alot. We used this changes for over an year so I am sure they work.

2023-09-07 09:08 UTC, SpraxDev requested changes
One thing I am not sure about - Rest looks great to me :)
Thanks for your interest in contributing

2023-09-07 09:08 UTC, SpraxDev commented on EpicSpawners-Plugin/src/main/java/com/craftaro/epicspawners/EpicSpawners.java
> +        if (Bukkit.getScheduler().isCurrentlyRunning(this.particleTask.getTaskId())) {
I'm not sure if `#isCurrentlyRunning` is the correct method here...
If I understand the [JavaDocs](https://hub.spigotmc.org/javadocs/spigot/org/bukkit/scheduler/BukkitScheduler.html#isCurrentlyRunning(int)) for it correctly, for repeating-tasks it actually tells you if they are running right now and not when they are idle and waiting for their next scheduled execution

Have you experienced weird behavior that could be related to that? Is there an issue in canceling a task when it has already been cancelled in the past?
> A repeating task might not be running currently, but will be running in the future.

2023-09-07 09:08 UTC, SpraxDev commented on EpicSpawners-Plugin/src/main/java/com/craftaro/epicspawners/EpicSpawners.java
> +        if (Bukkit.getScheduler().isCurrentlyRunning(this.spawnerCustomSpawnTask.getTaskId())) {
Same as some lines further up:

> I'm not sure if `#isCurrentlyRunning` is the correct method here...
> If I understand the [JavaDocs](https://hub.spigotmc.org/javadocs/spigot/org/bukkit/scheduler/BukkitScheduler.html#isCurrentlyRunning(int)) for it correctly, for repeating-tasks it actually tells you if they are running right now and not when they are idle and waiting for their next scheduled execution
> 
> Have you experienced weird behavior that could be related to that? Is there an issue in canceling a task when it has already been cancelled in the past?
> > A repeating task might not be running currently, but will be running in the future.

2023-09-25 16:39 UTC, SpraxDev commented
Hi @Tom18314, any updates on this?

2023-09-29 10:06 UTC, Tom18314 commented
@SpraxDev no, never had any issues with this.

2023-09-29 10:32 UTC, SpraxDev commented
@ceze88 I think you wanted to merge this together with some other change?

2023-09-29 10:57 UTC, ceze88 commented
I already made those changes

2023-09-29 11:59 UTC, merged